on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_chains:
    name: Validate chains.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate chains.json schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./chains.schema.json
          json_path_pattern: .*\/chains.json$